export const projects = [
  {
    title: 'NBA Dashboard',
    description: "Developed a full stack dashboard for NBA match statistics where users can check results, statistics for the most recent games by team, or history game statistics from 2014 - 2022.",
      image: '/images/nba-dashboard.png',
      tags: ['Java', 'Spring Boot', 'Spring MVC', 'React', 'H2', 'Spring Batch'],
    source: 'https://github.com/ZOZO-coding/nba-dashboard',
    visit: 'http://nbadashboard-env.eba-6juq95ur.us-east-2.elasticbeanstalk.com/',
    id: 0,
  },
  {
    title: 'Recipe Website with Next.js',
    description: "Created and deployed a recipe website with Next.js, HTML/CSS, and JavaScript, connected with a headless CMS - Contentful for data fetching.Implemented features including data fetching with Contentful, incremental static regeneration, and fallback pages.",
      image: '/images/zozo-recipe.png',
      tags: ['Next.js', 'Javascript', 'Contentful', 'HTML/CSS'],
    source: 'https://github.com/ZOZO-coding/zozo-recipe',
    visit: 'https://zozo-recipe.vercel.app/',
    id: 1,
  },
  {
    title: 'MERN Tech Interview Study Forum',
    description: "Using React, Node.js, Express & MongoDB to build a Full Stack MERN Application - users can post, like, comment on and manage study notes, and create to-do lists. Improved website security by providing user authentication using JWT, Bcrypt.",
      image: '/images/tech-interview-website.png',
      tags: ['Mongo', 'Express', 'React', 'Node'],
    source: 'https://github.com/ZOZO-coding/MERN_STACK',
    visit: 'https://zingy-parfait-4346f3.netlify.app',
    id: 2,
  },
  {
    title: 'E-Commerce-BestBuy-Mock',
    description:"Lead a team of 3 junior full stack developers to build a E-Commerce electronics website. The application is a MERN stack application, signed in users can browse products in different categories, and upload own used product.",
    image: '/images/project-electronics.png',
    tags: ['Mongo', 'Express', 'React', 'Node'],
    source: 'https://github.com/ZOZO-coding/Project_Electronics',
    visit: 'https://github.com/ZOZO-coding/Project_Electronics',
    id: 3,
  },
  {
    title: 'Youtube-Clone',
    description: "This is a React project to create a simplified Youtube website, using Rapid API for data fetching, and Material UI for front end renderings.",
      image: '/images/youtube-clone.png',
      tags: ['React', 'RapidAPI', 'Material-UI-v5'],
    source: 'https://github.com/ZOZO-coding/youtube_clone',
    visit: 'https://comfy-chebakia-326f85.netlify.app',
    id: 4,
  },
  {
    title: 'ZoZo-Campaign',
    description: "This is a front end campaign style website using Tailwind CSS to style the entire website.",
      image: '/images/zozo-campaign.png',
      tags: ['HTML', 'Javascript', 'Tailwind CSS'],
    source: 'https://github.com/ZOZO-coding/zozo-campaign',
    visit: 'https://zozo-campaign.onrender.com/',
    id: 5,
  },
  {
    title: 'ZoeyNinja',
    description: "This is a simplified version of fruit ninja using HTML, CSS and Javascript, the game supports 2 players and each player can record their best scores, and advance to higher difficulties. Zoey is the name of my 4-year-old Pekingese",
    image: '/images/zoey-ninja.png',
    tags: ['HTML', 'CSS', 'Javascript'],
    source: 'https://github.com/ZOZO-coding/project-fruitNinja',
    visit: 'https://delicate-cheesecake-00ac04.netlify.app',
    id: 6,
  },
  {
    title: 'ZoZo-Movieland',
    description: "This is a React application to create a movie searching website, using fetch API.",
    image: '/images/zozo-movieland.png',
    tags: ['React', 'CSS', 'Javascript'],
    source: 'https://github.com/ZOZO-coding/zozo-movieland',
    visit: 'https://github.com/ZOZO-coding/zozo-movieland',
    id: 7,
  },
  {
    title: 'Personal-Dashboard',
    description: "Created a personal dashboard with React and Redux, main features include: To Do List, Weather API and Calculator.",
    image: '/images/personal-dashboard.png',
    tags: ['React', 'Redux', 'CSS', 'Javascript'],
    source: 'https://github.com/ZOZO-coding/todolist',
    visit: 'https://zobuffytodolist.netlify.app',
    id: 8,
  },
  {
    title: 'Celtics-Mock',
    description: "Created a Boston Celtics website mock up, using HTML, CSS and Javascript.",
    image: '/images/celtics-mock.png',
    tags: ['HTML', 'CSS', 'Javascript'],
    source: 'https://github.com/ZOZO-coding/Dev/tree/main/Homeworks/week2/day1',
    visit: 'https://github.com/ZOZO-coding/Dev/tree/main/Homeworks/week2/day1',
    id: 9,
  },
];

export const TimeLineData = [
  { year: 2017, text: 'Started as a sales team leader', },
  { year: 2018, text: 'Worked as a project manager', },
  { year: 2021, text: 'Got my PMP certification', },
  { year: 2022, text: 'Started as a self-taught, freelance full stack developer', },
];